import { writable } from "svelte/store";
export let hisotry = writable([{
  name: "Delivery Express",
  tag: "@Delevery Company",
  price: "50 DA",
  time: "23 min",
  description: 'Delivery Express: Swift, Reliable Delivery – Your Packages in Safe Hands!',
},
{
  name: "Delivery Express",
  tag: "@Delevery Company",
  price: "50 DA",
  time: "23 min",
  description: 'Delivery Express: Swift, Reliable Delivery – Your Packages in Safe Hands!',
},
{
  name: "Delivery Express",
  tag: "@Delevery Company",
  price: "50 DA",
  time: "23 min",
  description: 'Delivery Express: Swift, Reliable Delivery – Your Packages in Safe Hands!',
},
{
  name: "Delivery Express",
  tag: "@Delevery Company",
  price: "50 DA",
  time: "23 min",
  description: 'Delivery Express: Swift, Reliable Delivery – Your Packages in Safe Hands!',
},
{
  name: "Delivery Express",
  tag: "@Delevery Company",
  price: "50 DA",
  time: "23 min",
  description: 'Delivery Express: Swift, Reliable Delivery – Your Packages in Safe Hands!',
},
{
  name: "Delivery Express",
  tag: "@Delevery Company",
  price: "50 DA",
  time: "23 min",
  description: 'Delivery Express: Swift, Reliable Delivery – Your Packages in Safe Hands!',
},
{
  name: "Delivery Express",
  tag: "@Delevery Company",
  price: "50 DA",
  time: "23 min",
  description: 'Delivery Express: Swift, Reliable Delivery – Your Packages in Safe Hands!',
},
{
  name: "Delivery Express",
  tag: "@Delevery Company",
  price: "50 DA",
  time: "23 min",
  description: 'Delivery Express: Swift, Reliable Delivery – Your Packages in Safe Hands!',
}]);